Issue #9: Request Model
hatchways/team-willow pull request #44
Opened 2022-01-16 19:09 UTC by jtingling

### What this PR does (required):
- A model for storing data about a dog sitting request.

### Any information needed to test this feature (required):
- Create a new document by providing: `userId`, `sitterId`, `date`, `start`, `end`, properties to a model create function.

2022-01-17 20:00 UTC, ezeilo-su requested changes
Looks good. Just a few comments to address, though. :smile:

2022-01-17 20:00 UTC, ezeilo-su commented on server/models/Request.js
> +        required: true,
Add a `ref` to `User` model

2022-01-17 20:29 UTC, jtingling commented on server/models/Request.js
> +        required: true,
I'll add the ref on next commit.

2022-01-17 20:29 UTC, jtingling commented on server/models/Request.js
> +        required: true,
I'll add the ref on next commit.

2022-01-18 17:05 UTC, moffatethan requested changes
Just some changes on the code style - overall, good work. Not sure why the controller work is in this ticket. But we can merge the two together.

2022-01-18 17:05 UTC, moffatethan commented on server/models/Request.js
> +    },
Let's remove these for now

2022-01-18 19:26 UTC, jtingling commented on server/controllers/request.js
> +    });
> Just some changes on the code style - overall, good work. Not sure why the controller work is in this ticket. But we can merge the two together.

I realized I mistakenly committed the controller work into this PR so I tried to revert back one commit, stashed the changes for controller and made a new branch off develop and reapplied the stashed commit to the new branch for #45.  This is why both #44 and #45 include duplicate code.

2022-01-26 00:57 UTC, moffatethan requested changes
Please address the merge conflicts

2022-01-26 01:58 UTC, jtingling commented
The merge conflict has been resolved.

2022-02-01 03:52 UTC, moffatethan approved these changes

2022-02-01 14:44 UTC, merged