Issue #8: Request Controller
hatchways/team-willow pull request #45
Opened 2022-01-16 19:58 UTC by jtingling

### What this PR does (required):
- Create, read, update operations on Request model for dog sitting.

### Any information needed to test this feature (required):
- Register two users.
- Set a environment variable `TOKEN` with a encoded JWT token of the dog owner;
- Re-assign `userId` and `sitterId` values to the `id` values of the  users you registered in `models.spec.js`.
- On the command line, run `npm run testRequets`.

2022-01-17 19:49 UTC, ezeilo-su requested changes
Good work with this one. A few comments to address, though.

2022-01-17 19:49 UTC, ezeilo-su commented on server/controllers/request.js
> +    const userId = req.query.userId;
You need to return a `400` if this field is missing

2022-01-17 19:49 UTC, ezeilo-su commented on server/controllers/request.js
> +    const { userId, sitterId, date, start, end } = req.body;
Please validate the request body and returna `400` if any required filed is missing

2022-01-17 19:49 UTC, ezeilo-su commented on server/controllers/request.js
> +    });
You can use `await` here since the function is an `async` type

2022-01-17 19:49 UTC, ezeilo-su commented on server/controllers/request.js
> +    });
Use `await` with an `async` function

2022-01-17 19:49 UTC, ezeilo-su commented on server/controllers/request.js
> +    });
Same as the comments above

2022-01-17 19:49 UTC, ezeilo-su commented on server/models/Request.js
> +        required: true,
This should reference the `User` model

2022-01-17 19:49 UTC, ezeilo-su commented on server/models/Request.js
> +        required: true,
Add a `ref` to the `User` model

2022-01-21 16:53 UTC, ezeilo-su reviewed
Thank you for making the requested changes. Please wait for the team to approve before you can merge.
Happy coding!

2022-01-21 21:44 UTC, moffatethan approved these changes

2022-01-24 15:04 UTC, merged